### ISSUE TITLE
under the same  wifi , but it don't work  

### ISSUE THREAD

**Issue by blockChainB** [S3Jensen/iRET#12]
192.168.31.120 
Rejected our connection request.

![shot](https://cloud.githubusercontent.com/assets/11595694/22197104/78f0a15e-e18b-11e6-9389-085a35b614b4.png)

**Comment by masbog** [comment]
try running using terminal and verbose it... maybe you miss some tools...

# python /Applications/iRE.app/iRE_Server.py -v

**Comment by naveen12** [comment]
did the same command, in log it showing issue like below
Tests-iPod-touch:/Applications/iRE.app root# python iRE_Server.py -v
Starting Server...
/
ls: cannot access /var/mobile/Applications/*/*.app/Info.plist: No such file or directory

192.168.20.41 - - [28/Nov/2017 12:59:08] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.20.41', 31541)
Traceback (most recent call last):
  File "/usr/lib/python2.5/SocketServer.py", line 222, in handle_request
    self.process_request(request, client_address)
  File "/usr/lib/python2.5/SocketServer.py", line 241, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.5/SocketServer.py", line 254, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.5/SocketServer.py", line 522, in __init__
    self.handle()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 316, in handle
    self.handle_one_request()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 299, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.5/socket.py", line 346, in readline
    data = self._sock.recv(self._rbufsize)
error: (54, 'Connection reset by peer')
----------------------------------------
/
ls: cannot access /var/mobile/Applications/*/*.app/Info.plist: No such file or directory

192.168.20.41 - - [28/Nov/2017 13:00:02] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.20.41', 31545)
Traceback (most recent call last):
  File "/usr/lib/python2.5/SocketServer.py", line 222, in handle_request
    self.process_request(request, client_address)
  File "/usr/lib/python2.5/SocketServer.py", line 241, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.5/SocketServer.py", line 254, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.5/SocketServer.py", line 522, in __init__
    self.handle()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 316, in handle
    self.handle_one_request()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 299, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.5/socket.py", line 346, in readline
    data = self._sock.recv(self._rbufsize)
error: (54, 'Connection reset by peer')
----------------------------------------
/
ls: cannot access /var/mobile/Applications/*/*.app/Info.plist: No such file or directory

and my application was installed on /var/mobile/Containers/Data/Application
ipod touch, iOS 9.3.5

**Comment by naveen12** [comment]
Later it showing but in selection my app was not showing
could you please tell me the path of code where i need update my app location in which file
