### ISSUE TITLE
No application shown under applist

### ISSUE THREAD

**Issue by fr33wi11** [S3Jensen/iRET#4]
I have application list drop down with no application.  Upon digging I found following error, when ran the server from terminal:
ls: cannot access /var/mobile/Applications/_/_.app/Info.plist: No such file or directory

I am running it on IPad air2, iOS 8.1

any advise?

**Comment by S3Jensen** [comment]
1) What is the actual directory name of the application that is being referenced?

2) I cannot guarantee iRET will work correctly on iOS 8.x, as I have not completed all of my updates for this version.

Date: Fri, 21 Nov 2014 15:37:54 -0800

**Comment by Slotos** [comment]
`/var/mobile/Applications` is not there in iOS8 anymore. You're looking for `/private/var/db/stash/*/Applications/*.app/Info.plist`. There's also no guid in executable path anymore either.

Probably there's a way to replace that first `*` with a definite folder, but I haven't looked into it yet.

update: `/Applications` links to `/private/var/db/stash/{stash_id}'

another update:
So, if you want all applications, there're three path patterns to query. I've been focusing my "fixing" on one app, overlooking other patterns.

The other two patters are:
- `/private/var/mobile/Containers/Bundle/Application/*/*.app` - the first star will let you find screenshots if you capture it. My guess is these are appstore applications
- /System/Library/CoreServices/*.app/ - SpringBoard resides here

I'm stopping at this for now.

**Comment by Kenjiz0r** [comment]
Same problem ios 8.1 empty list of apps

**Comment by ankitbharathan** [comment]
when we can expect  ios 8.x support ??

**Comment by fr33wi11** [comment]
Okay.  Thanks.  So now the million dollar question : when you plan to provide iOS 8.x support?

**Comment by masbog** [comment]
here, change all .sh file on iRE.app like this or see my repo, where waiting pull request accepted

```
mas-iPhone:/Applications/iRE.app root# grep -R "/var/mobile/Applications/" .
./Binary.sh:#binFile=$(find /var/mobile/Applications/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Database.sh:#databases=$(find /var/mobile/Applications/$AppID -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' -type f)
./Headers.sh:   #binFile=$(find /var/mobile/Applications/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Log.sh:#logs=$(find /var/mobile/Applications/$AppID -name '*.log' -o -name '*.txt' -type f)
./Menu.sh:#guids=$(ls /var/mobile/Applications/*/*.app/Info.plist |sort | cut -d"/" -f5)
./Menu.sh:    #name=$( ls /var/mobile/Applications/$a/*.app/Info.plist | cut -d"/" -f6 | cut -d. -f1 )
./PList.sh:#PLists=$(find /var/mobile/Applications/$AppID -name '*.plist' -type f)
./Screenshot.sh:        #image=$(find /var/mobile/Applications/"$AppID"/Library/Caches -name '*.png' -type f)
./Theos.sh:         #InfoFile=$(find /var/mobile/Applications/"$AppID" -name Info.plist -type f)
mas-iPhone:/Applications/iRE.app root# grep -R "/private/var/mobile/Containers/Bundle/Application/" .
./Binary.sh:binFile=$(find /private/var/mobile/Containers/Bundle/Application/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Database.sh:database=$(find /private/var/mobile/Containers/Bundle/Application/$AppID -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' -type f)
./Headers.sh:   binFile=$(find /private/var/mobile/Containers/Bundle/Application/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Log.sh:logs=$(find /private/var/mobile/Containers/Bundle/Application/$AppID -name '*.log' -o -name '*.txt' -type f)
./Menu.sh:guids=$(ls /private/var/mobile/Containers/Bundle/Application/*/*.app/Info.plist |sort | cut -d"/" -f8)
./Menu.sh:    name=$( ls /private/var/mobile/Containers/Bundle/Application/$a/*.app/Info.plist | cut -d"/" -f9 | cut -d. -f1 )
./PList.sh:PLists=$(find /private/var/mobile/Containers/Bundle/Application/$AppID -name '*.plist' -type f)
./Screenshot.sh:    image=$(find /private/var/mobile/Containers/Bundle/Application/"$AppID"/Library/Caches -name '*.png' -type f)
./Theos.sh:         InfoFile=$(/private/var/mobile/Containers/Bundle/Application/ "$AppID" -name Info.plist -type f)
```

now iRET work on my iOS 9 Jailbroken device... :)

![image](https://cloud.githubusercontent.com/assets/663374/13506134/1ab19f76-e1af-11e5-8d26-6c9c9610cc5e.png)

**Comment by saikun** [comment]
@masbog I was wondering if you could update package(iRET.deb) in your branch.
I try hard to build package(*.deb) from source code but it is not succeed.

**Comment by masbog** [comment]
@saikun just install from latest build debian package of iRET if you fail to build it, then replace all the .sh files from my repo... .sh files are located on 

> /Applications/iRE.app/

 :)

**Comment by S3Jensen** [comment]
@saikun @masbog is correct. Just install from the current iRET debian package. Once installed, copy all of the updated .sh files into the /Applications/iRE.app directory. 

Thanks @masbog for updating this! I've been so busy I just couldn't find the time. I'm glad people are still interested in it and using it. :)

**Comment by saikun** [comment]
@masbog @S3Jensen Thanks a lot! 
iRE_Server.py is working after I replaced *.sh as you told me.
Yet, i still have some problem. 

I found that iRE_Server.py works fine but other tools doesn't work.
For example:
/Binary?AppID=[AppID]
/Binary?AppID=[AppID]
192.168.1.115 - - [29/Mar/2016 15:37:15] "GET /Binary?AppID=[AppID] HTTP/1.1" 200 -
error: otool: can't open file: /private/var/mobile/Containers/Bundle/Application/[AppID]/[AppName].app/Frameworks/libswiftContacts.dylib

At the least, Keychain-Dumper worked when I executed command by myself.
So, maybe I have forgotten some settings on my phone or iRET.
or, Is it problem on iOS 8?

**Comment by masbog** [comment]
@saikun try open otool manual from your terminal or remote it using SSH, what the message shown?
for keychain-dumper, try edit the toolPaths.txt like mine: 

> root# cat toolPaths.txt 
> otool:/usr/bin/otool
> sqlite3:/usr/bin/sqlite3
> file:/usr/bin/file
> plutil:/usr/bin/plutil
> theos:/private/var/theos
> dumpdecrypted:/Library/dumpdecrypted.dylib /masbog/dumpdecrypted/dumpdecrypted.dylib
> keychainDumper:/masbog/Keychain-Dumper/keychain_dumper /private/var/db/stash/_.C0mBXy/Applications/iNalyzer5.app/keychain_dumper /usr/bin/keychain_dumper
> classDumpZ:/usr/bin/class-dump-z
> perl:/usr/local/bin/perl

**Comment by saikun** [comment]
@masbog If I executed otool on terminal it's seem like work.
The target path is also seem like good.
/private/var/mobile/Containers/Bundle/Application/[AppID]/[AppName].app/Frameworks/libswiftContacts.dylib

If I edit toolPaths.txt for myself and run iRE_Server.py then toolPaths.txt will reset.
Should I edit iRE_Server.py ?

**Comment by masbog** [comment]
@saikun nope, argh.... may this http://stackoverflow.com/questions/32526526/invalid-swift-support-files-don-t-match can fix your issue... 

> Copy all libswiftXxx.dylib files from SwiftSupport/iphoneos/ into Products/Applications/YourApp.ipa/Frameworks/ and overwrite

**Comment by saikun** [comment]
@masbog Thanks a lot for your kind advice.
I'll try to replace the dylib files after some days.

**Comment by masbog** [comment]
your welcome 😄

Twitter @MasBog

**Comment by umarhyatt** [comment]
Hi. Did anyone find a definite solution to this problem? I am having same problem and my device is running ISO 8.4.

**Comment by askmegit** [comment]
@masbog I change all .sh file on iRE.app like this

```
iPhone:/Applications/iRE.app root# grep -R "/var/mobile/" .
./Binary.sh:  binFile=$(find /private/var/mobile/Containers/Bundle/Application/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Binary.sh:  binFile=$(find /var/mobile/Applications/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Database.sh:  database=$(find /private/var/mobile/Containers/Bundle/Application/$AppID -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' -type f)
./Database.sh:  databases=$(find /var/mobile/Applications/$AppID -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' -type f)
./Headers.sh:    binFile=$(find /private/var/mobile/Containers/Bundle/Application/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Headers.sh:    binFile=$(find /var/mobile/Applications/"$AppID"/*.app -type f -exec file {} \; | grep Mach-O | cut -d":" -f1)
./Log.sh:  logs=$(find /private/var/mobile/Containers/Bundle/Application/$AppID -name '*.log' -o -name '*.txt' -type f)
./Log.sh:  logs=$(find /var/mobile/Applications/$AppID -name '*.log' -o -name '*.txt' -type f)
./Menu.sh:  guids=$(ls /private/var/mobile/Containers/Bundle/Application/*/*.app/Info.plist |sort | cut -d"/" -f8)
./Menu.sh:  guids=$(ls /var/mobile/Applications/*/*.app/Info.plist |sort | cut -d"/" -f5)
./Menu.sh:      name=$( ls /private/var/mobile/Containers/Bundle/Application/$a/*.app/Info.plist | cut -d"/" -f9 | cut -d. -f1 )
./Menu.sh:      name=$( ls /var/mobile/Applications/$a/*.app/Info.plist | cut -d"/" -f6 | cut -d. -f1 )
./PList.sh:  PLists=$(find /private/var/mobile/Containers/Bundle/Application/$AppID -name '*.plist' -type f)
./PList.sh:  PLists=$(find /var/mobile/Applications/$AppID -name '*.plist' -type f)
./Screenshot.sh:        applicationBundelIDLoc=$(grep -n 'CFBundleIdentifier' /private/var/mobile/Containers/Bundle/Application/$AppID/*/Info.plist | sed 's/:.*//')
./Screenshot.sh:        applicationBundelID=$(cat /private/var/mobile/Containers/Bundle/Application/$AppID/*/Info.plist | sed -n "${applicationBundelIDLoc}p" | sed 's/^.*<string>//' | sed 's/<\/string>.*//')
./Screenshot.sh:        image=$(find /private/var/mobile/Containers/Data/Application/*/Library/Caches/Snapshots/$applicationBundelID/ -maxdepth 1 -name '*.png' -type f)
./Screenshot.sh:        image=$(find /var/mobile/Applications/"$AppID"/Library/Caches -name '*.png' -type f)
./Theos.sh:        InfoFile=$(/private/var/mobile/Containers/Bundle/Application/ "$AppID" -name Info.plist -type f)
./Theos.sh:        InfoFile=$(find /var/mobile/Applications/"$AppID" -name Info.plist -type f)
Binary file ./dumpdecrypted.dylib matches
```

then I connect like this

```
iPhone:/Applications/iRE.app root# python iRE_Server.py
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Starting Server...
```

connect
![2016-08-21 2 18 50](https://cloud.githubusercontent.com/assets/17285243/17833037/aca2987e-6745-11e6-8d71-484fc35940fc.png)
terminat show

```
ls: cannot access /private/var/mobile/Containers/Bundle/Application/*/*.app/Info.plist: No such file or directory

192.168.1.5 - - [21/Aug/2016 02:19:52] "GET / HTTP/1.1" 200 -
/favicon.ico
```

there no app list I can select,and in path /private/var/mobile/Containers/Bundle/Application no director.who can help me,Tks!

**Comment by masbog** [comment]
ah... your problem is on your python... i forgot which repo support ios 9 and 64bit...

**Comment by epinapala** [comment]
@masbog @S3Jensen Thanks a lot! I was able to replace the ssh files from command line, and boom!! all apps are showing up. 

tested on jb Ipad air running 9.0.2

**Comment by masbog** [comment]
@epinapala did you mean .sh files? hehehehehe.... you're welcome dude...
